apiVersion: v1
kind: Service
metadata:
  name: java-spring-service
spec:
  selector:
    app: java-spring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
